import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Button } from '@/components/ui/button'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { SidebarNav } from '@/components/layout/SidebarNav'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <div className="md:grid md:grid-cols-[240px_1fr]">
            <div className="sticky top-0 z-20 md:h-[100svh]">
              <SidebarNav />
            </div>
            <div className="min-h-[100svh]">{children}</div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}
